### ISSUE TITLE
Fail to install `plover-plugins-manager` because of missing `readme-renderer`

### ISSUE THREAD

**Issue by leira** [dnaq/plover-flake#12]
`I tried to install Plover with `plover_plugins_manager` and `plover_machine_hid by adding these lines in my `configuration.nix` (the `inputs` is from the `flake.nix` in my configuration).

```
  environment.systemPackages = with pkgs; [
...
    (inputs.plover-flake.packages.${system}.plover-with-plugins (ps: with ps; [
      plover_plugins_manager
      plover_machine_hid
    ]))
  ];

```

It installed successfully without `plover_plugins_manager`. But with `plover_plugins_manager`, it failed because of unmet dependency of `readme-renderer`. `readme-renderer` is in nixpkgs, but I'm not sure how to specify it for `plover_plugins_manager` with the current structure.

```
building the system configuration...
error: builder for '/nix/store/rsri22kmwmrv7y2rgn2jjjk8nr1h3jlz-python3.10-plover_plugins_manager-0.7.1.drv' failed with exit code 1;
       last 10 log lines:
       > adding 'plover_plugins_manager-0.7.1.dist-info/RECORD'
       > removing build/bdist.linux-x86_64/wheel
       > Finished executing setuptoolsBuildPhase
       > installing
       > Executing pipInstallPhase
       > /build/plover_plugins_manager-0.7.1/dist /build/plover_plugins_manager-0.7.1
       > Processing ./plover_plugins_manager-0.7.1-py3-none-any.whl
       > ERROR: Could not find a version that satisfies the requirement readme-renderer[md] (from plover-plugins-manager) (from versions: none)
       > ERROR: No matching distribution found for readme-renderer[md]
       >
       For full logs, run 'nix log /nix/store/rsri22kmwmrv7y2rgn2jjjk8nr1h3jlz-python3.10-plover_plugins_manager-0.7.1.drv'.
```

I know I can always install plugins with Nix without plugin manager. But I like the flexibility to try some plugins easily. Also, I'm afraid some of the plugins might have their own dependency issue similar to this, though I haven't try more.

**Comment by dnaq** [comment]
The plugin manager won't work with this flake (even when adding the dependencies needed), since it requires write access to the python user site, which is something this flake doesn't allow. If you want a flake containing the plugin manager together with a user writable user site you can look at dnaq/plover-flake instead, which I'm going to deprecate in the near future.
